# Generated by Django 5.2.5 on 2025-08-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='video',
            name='order',
        ),
        migrations.RemoveField(
            model_name='video',
            name='youtube_id',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
